### ISSUE TITLE
ESDoc Hosting Service

### ISSUE THREAD

**Issue by h13i32maru** [stremlenye/immutable-http#16]
Hi!
I am ESDoc developer and thanks for using ESDoc :smile: 

I released [ESDoc Hosting Service](https://doc.esdoc.org) :rocket: 
Register your repository Git URL, this service automatically generate documentation.
If you are interested, please try to use it.
Thanks

**Comment by stremlenye** [comment]
Hi
Sorry for late answer.
Thank for service! Just tried – looks awesome!
https://doc.esdoc.org/github.com/stremlenye/immutable-http/
Will it update automatically somehow or should I trigger it by hands?

**Comment by h13i32maru** [comment]
Hi
Sorry for delay.

> Will it update automatically somehow or should I trigger it by hands?

Not automatically, please trigger it by hands. 

Thanks.

**Comment by stremlenye** [comment]
:+1:
